import { NextRequest, NextResponse } from 'next/server'

interface Summary {
  id: string
  title: string
  content: string
  summaryType: string
  wordCount: number
  createdAt: string
  documentName: string
}

export async function POST(request: NextRequest) {
  try {
    const summary: Summary = await request.json()

    if (!summary || !summary.content) {
      return NextResponse.json(
        { error: 'Invalid summary data' },
        { status: 400 }
      )
    }

    // Create TXT content
    const txtContent = `Document Summary
===================

Title: ${summary.title || 'Untitled'}
Document: ${summary.documentName}
Summary Type: ${summary.summaryType}
Word Count: ${summary.wordCount}
Generated: ${new Date(summary.createdAt).toLocaleString()}

Summary Content:
----------------

${summary.content}

---
Generated by AI Document Summarizer
`

    // Create response with TXT file
    const response = new NextResponse(txtContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="summary-${summary.id}.txt"`
      }
    })

    return response
  } catch (error) {
    console.error('TXT export error:', error)
    return NextResponse.json(
      { error: 'Failed to export summary as TXT' },
      { status: 500 }
    )
  }
}